const config = {
  levels: [
    {
      levelNum: 1,
      levelName: 'Academy',
      levelColor: 'white',
      levelButtonColor: 'rgba(255,255,255,0.5)',
      levelTitleColor: '#333',
      levelAvatar: 'academy.png',
    },
    {
      levelNum: 2,
      levelName: 'Gennin',
      levelColor: 'yellow',
      levelButtonColor: 'rgba(255,255,0,0.5)',
      levelTitleColor: '#333',
      levelAvatar: 'academy.png',
    },
    {
      levelNum: 3,
      levelName: 'Chuunin',
      levelColor: 'darkorange',
      levelButtonColor: 'rgba(255,140,0,0.5)',
      levelAvatar: 'gennin.png',
    },
    {
      levelNum: 4,
      levelName: 'Jounin',
      levelColor: 'orangered',
      levelButtonColor: 'rgba(255,69,0,0.5)',
      levelTitleColor: '#333',
      levelAvatar: 'chuunin.png',
    },
    {
      levelNum: 5,
      levelName: 'Special Jounin',
      levelColor: 'lime',
      levelButtonColor: 'rgba(0,255,0,0.5)',
      levelTitleColor: '#333',
      levelAvatar: 'jounin.png',
    },
    {
      levelNum: 6,
      levelName: 'Kage',
      levelColor: 'blue',
      levelButtonColor: 'rgba(0,0,255,0.5)',
      levelTitleColor: '#fff',
      levelAvatar: 'special-jounin.png',
    },
    {
      levelNum: 7,
      levelName: 'ANBU',
      levelColor: 'purple',
      levelButtonColor: 'rgba(128,0,128,0.5)',
      levelTitleColor: '#fff',
      levelAvatar: 'kage.png',
    },
    {
      levelNum: 8,
      levelName: 'S-Class',
      levelColor: 'maroon',
      levelButtonColor: 'rgba(128,0,0,0.5)',
      levelTitleColor: '#fff',
      levelAvatar: 'anbu.png',
    },
    {
      levelNum: 9,
      levelName: 'Code Ninja',
      levelColor: 'red',
      levelButtonColor: 'rgba(255,0,0,0.5)',
      levelTitleColor: '#fff',
      levelAvatar: 's-class.png',
    },
  ],
};

export default config;
